// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHl19oJBvUEMh2enZebJiuauCud9VZ-yQ',
    appId: '1:435680585810:web:36c690c1694a4092bf178b',
    messagingSenderId: '435680585810',
    projectId: 'carbon-ed1ce',
    authDomain: 'carbon-ed1ce.firebaseapp.com',
    storageBucket: 'carbon-ed1ce.firebasestorage.app',
    measurementId: 'G-SNZPNWC61T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ymN3-s8SQ48n-MsCzaT46MEPV9gwaF8',
    appId: '1:435680585810:android:76e3f4677018f97abf178b',
    messagingSenderId: '435680585810',
    projectId: 'carbon-ed1ce',
    storageBucket: 'carbon-ed1ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCGDY9px3fvvKJboGKdtCIXiLCVkC-HiI',
    appId: '1:435680585810:ios:8be08b0c71ffe20dbf178b',
    messagingSenderId: '435680585810',
    projectId: 'carbon-ed1ce',
    storageBucket: 'carbon-ed1ce.firebasestorage.app',
    iosBundleId: 'com.example.carbonFootprint',
  );
}
